### ISSUE TITLE
Is it possible to have nonnullable properties in the generated code for fields with default value?

### ISSUE THREAD

**Issue by fastestdevalive** [jonasbark/openapi_dart#6]
Hi there

I have been trying to generate the code such that the generated properties are not optional but it looks like that's not possible. 

For example, for a class like this:
```
User:
  type: object
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
  required:
    - name
    - id
  default:
    - name: ''
```
Does it make sense if the name property is actually non-nullable or non-optional in the generated code?  If this request does make sense, feel free to put me in the right direction.
